GET http://localhost:5297/games/

###

POST http://localhost:5297/games 
Content-Type: application/json

{
    "name": "Gta VI",
    "genre": "Action-adventure",
    "price": 159.99,
    "releaseDate": "2026-03-03" 
}

###
PUT http://localhost:5297/games/1
Content-Type: application/json

{
    "name": "Pro Evolution Soccer 2013",
    "genre": "Sports",
    "price": 29.99,
    "releaseDate": "2012-12-12" 
}

###
DELETE http://localhost:5297/games/3